spring.application.name=original1

spring.datasource.url=jdbc:postgresql://dpg-d81o43g3kofs73cu5ic0-a.frankfurt-postgres.render.com/fusis?sslmode=require
spring.datasource.username=melih
spring.datasource.password=f8UdnjACdyZTIISxvjlnT8RnRc0bqqTu
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8080




# Kendi giriş bilgilerini tanımla
spring.security.user.name=melih
spring.security.user.password=12345


